appdaemon:
  latitude: 52.2297
  longitude: 21.0122
  elevation: 100
  time_zone: Europe/Warsaw
  plugins:
    HASS:
      type: hass
      ha_url: !secret ha_url
      token: !secret ha_token
logs:
  main_log:
    filename: /conf/logs/appdaemon.log
  error_log:
    filename: /conf/logs/error.log
  debug_log:
    filename: /conf/logs/debug.log
    level: DEBUG